### PR TITLE
Add seed support

### PR DESCRIPTION
**Pull request by tearsofphoenix**
1.  seed support: to create keypair from seed;
2. add mocha test.

### CODE REVIEW

**Comment by buu700** [comment]
Thanks for the PR! This exact feature is something that's been requested in the past, so your effort is much appreciated.

Initial comments:

* To make reviewing this easier, could you split the seed support and unit tests into two separate PRs?

* This is a big set of changes just to add that feature. Nothing wrong with rewriting large parts of the library for a separately maintained fork, but as a PR it unnecessarily breaks backwards compatibility with this modules's existing interface.

  To keep this as conservative as possible, could you implement it as simply an optional parameter to `keyPair`? i.e.

  ```
  /**
   * Generates key pair.
   * @param seed Optional seed to generate deterministic key pair.
   */
  keyPair (seed?: Uint8Array) : Promise<{privateKey: Uint8Array; publicKey: Uint8Array}>;
  ```

* For consistency with the existing code, can you use tabs for indentation?

* The package.json URL should remain git://github.com/cyph/ntru.js.git.

* I don't think your change to ntru.c is the correct way to handle seeding. The current implementation uses `ntru_crypto_drbg_`**`external`**`_instantiate` to directly plug libsodium's `randombytes_buf` function into NTRU. However, for seeding, [the NTRU readme](https://github.com/NTRUOpenSourceProject/NTRUEncrypt) documents a different function `ntru_crypto_drbg_instantiate` that can be used to seed its internal DRBG, which is what we would want to do here if I'm not mistaken.

  Adapting their `get_entropy` example would be straightforward; in place of "`getrandombyte`", just iterate through the seed and return 0 if you're already past the last byte.

**Comment by tearsofphoenix** [comment]
1.  make seed an optional parameter
2. tab for indent
3. fix git url in `package.json`
4. use `ntru_crypto_drbg_instantiate`

**Comment by buu700** [comment]
Thanks, this is closer. What I actually had in mind, though, is that the custom seed logic would be entirely self-contained within `ntru.keyPair` (i.e. no new `ntru.dispose` function or similar). So the C would look something like this:

```
long generate_keypair (
	uint8_t* public_key,
	uint8_t* private_key,
	DRBG_HANDLE keygen_drbg
) {
	return ntru_crypto_ntru_encrypt_keygen(
		keygen_drbg,
		PARAMS,
		&public_key_len,
		public_key,
		&private_key_len,
		private_key
	);
}

long ntrujs_keypair (
	uint8_t* public_key,
	uint8_t* private_key
) {
	return generate_keypair(public_key, private_key, drbg);
}

long ntrujs_keypair_with_seed (
	uint8_t* public_key,
	uint8_t* private_key,
	uint8_t* seed,
	long seed_len
) {
	DRBG_HANDLE keygen_drbg;

	/* Use the seed and ntru_crypto_drbg_instantiate here */

	long rc = generate_keypair(public_key, private_key, keygen_drbg);
	ntru_crypto_drbg_uninstantiate(keygen_drbg);
	return rc;
}
```

As far as my comments about keeping the change set conservative, what I meant is that there are a lot of small arbitrary changes that aren't needed for adding this feature, like rewriting most of post.js, changing the byte values in the interface from `Promise<number>` to `number` (more correctly, `number|undefined`), and miscellaneous whitespace changes such as:

screen shot 2018-01-26 at 4 32 36 pm

I don't mind doing some minor cleanup while merging, so no need to pore over the diff and make it as small as humanly possible; but it will be harder for me to review what's actually changed if I look at `ntru.keyPair` and the diff shows it as [an entirely new function](https://github.com/cyph/ntru.js/pull/3/files#diff-0c26e36ae831d8966471fd10e64f1cbeR55) rather than a modification of the existing one.

**Comment by ovanwijk** [comment]
Hi, is there any progress on this? Would be awesome to deterministicly generate key pairs!

**Comment by tearsofphoenix** [comment]
@ovanwijk  You'd better use this instead [ntrujs](https://github.com/IDWMaster/ntrujs)

**Comment by ovanwijk** [comment]
@tearsofphoenix problem is that it isn't webassembly, because I want to use it in the browser. And the licence is GPLv3. The components I make will be open source but I want them under MIT and not GPLv3.

I understand the reason for GPL since the makers of NTRU allowed this as the opensource variant( as I see it is abuse of opensource) but the patents were made public last december and placed under the creative commons. So anything goes now. (So when less restrictively licensed I indeed consider it)

Reason I like this lib is that works in the browser, so people can actually generate their keys locally. (And honestly I am not much of C/Rust/Webassembly/Emscripten guy so when I found this I was very happy!)

Cheers

**Comment by buu700** [comment]
FWIW, if you're up to it and know at least a little bit of C (and JS/TypeScript), I think there's enough between the work @tearsofphoenix has done so far and my comments above that it wouldn't be too much effort to piece together a new PR that fully implements the feature.

(I'd do it myself if I had enough free time, and may still come back and do it myself for fun anyway later in the year if it hasn't already been done by then.)

**Pull request closed without merging**
